import type { ExecMember } from "@/types/exec-board-type";

export const executiveMembers: ExecMember[] = [
  {
    role: "President",
    name: "Safiya Menk",
    pronouns: "She/Her",
    major: "Computer Science",
    year: "Senior",
    linkedin: "https://www.linkedin.com/in/safiyamenk/",
    image: "https://emergingcoders.org/Safiya.jpeg",
    email: "safiyamenk2025@u.northwestern.edu",
    isisFound: true,
  },
  {
    role: "Vice President",
    name: "Ethan Piñeda",
    pronouns: "He/They",
    major: "Computer Science & Data Science",
    year: "Senior",
    linkedin: "https://www.linkedin.com/in/ethanpineda/",
    image: "https://emergingcoders.org/Ethan.jpeg",
    email: "ethanpineda2025@u.northwestern.edu",
    isisFound: true,
  },
  {
    role: "Secretary",
    name: "Sydney Hoppenworth",
    pronouns: "She/They",
    major: "Computer Science",
    year: "Junior",
    linkedin: "https://www.linkedin.com/in/sydney-hoppenworth",
    image: "https://emergingcoders.org/Sydney.jpg",
    email: "sydneyhoppenworth2026@u.northwestern.edu",
  },
  {
    role: "Social Media Chair",
    name: "Eden Kim",
    pronouns: "She/Her",
    major: "Computer Science",
    year: "Junior",
    linkedin: "",
    image: "https://emergingcoders.org/Eden.jpg",
    email: "edenkim2025@u.northwestern.edu",
  },
  {
    role: "Treasurer",
    name: "Samreen Ibrahim",
    pronouns: "She/Her",
    major: "Computer Science",
    year: "Junior",
    linkedin: "",
    image: "https://emergingcoders.org/Samreen.jpeg",
    email: "",
  },
  {
    role: "Webmaster",
    name: "Desmond Yayra",
    pronouns: "He/They",
    major: "Computer Science",
    year: "Senior",
    linkedin: "https://www.linkedin.com/in/ethanpineda/",
    image: "https://emergingcoders.org/Desmond.jpg",
    email: "desmondadanuty2025@u.northwestern.edu",
  },
  {
    role: "Professional Liaison",
    name: "Yafet Hailu",
    pronouns: "He/Him",
    major: "Computer Engineering & HCI Certificate",
    year: "Junior",
    linkedin: "https://www.linkedin.com/in/yafet-hailu-a8b854205/",
    image: "https://emergingcoders.org/Yafet.jpg",
    email: "YafetHailu2026@u.northwestern.edu",
  },
];
