import type { ExecMember } from "@/types/exec-board-type";

export const executiveMembers2526: ExecMember[] = [
  {
    role: "President",
    name: "Sydney Hoppenworth",
    pronouns: "She/They",
    major: "Computer Science",
    year: "Junior",
    linkedin: "https://www.linkedin.com/in/sydney-hoppenworth",
    image: "/exec-pictures/sydney.jpeg",
    email: "SydneyHoppenworth2026@u.northwestern.edu",
  },
  {
    role: "Marketing Chair",
    name: "Marissa Rocha Rangel",
    major: "Computer Science",
    year: "First-Year",
    pronouns: "She/Her",
    linkedin: "https://www.linkedin.com/in/marissa-rocha-764a19281/",
    image: "/exec-pictures/marissa.jpeg",
    email: "MarissaRochaRangel2028@u.northwestern.edu",
  },
  {
    role: "Secretary",
    name: "Michelle Ordonez Campos",
    major: "Computer Science",
    year: "Sophomore",
    pronouns: "She/Her",
    linkedin: "https://www.linkedin.com/in/mordonez719/",
    image: "/exec-pictures/michelle.jpeg",
    email: "MichelleOrdonezCampos2027@u.northwestern.edu",
  },
  {
    role: "External Coordinator",
    name: "Joanna Echeverri Porras",
    pronouns: "She/Her",
    major: "Computer Science",
    year: "Sophomore",
    linkedin:
      "https://www.linkedin.com/in/joanna-ep?miniProfileUrn=urn%3Ali%3Afs_miniProfile%3AACoAADuwj-wBV6vE5evg2lfQdfvHXy2WPyP0jMM&lipi=urn%3Ali%3Apage%3Ad_flagship3_search_srp_all%3BjUOheGLeT%2F%2B0K4QbZyteVw%3D%3D",
    image: "/exec-pictures/joanna.jpg",
    email: "JoannaEcheverriPorras2027@u.northwestern.edu",
  },
  {
    role: "Technical Development Chair",
    name: "Keigo Healy",
    major: "Computer Science",
    year: "First-Year",
    pronouns: "He/Him",
    linkedin: "https://www.linkedin.com/in/keigo-healy-3a456a278/",
    image: "/exec-pictures/keigo.jpg",
    email: "KeigoHealy2028@u.northwestern.edu",
  },
  {
    role: "Professional Liaison",
    name: "Lana Alnajm",
    major: "Data Science, Social Policy",
    year: "First-Year",
    pronouns: "She/Her",
    linkedin:
      "https://www.linkedin.com/in/lana-alnajm-451b532a6/?trk=organization_guest_main-feed-card-text",
    image: "/exec-pictures/lana.jpeg",
    email: "LanaAlnajm2028@u.northwestern.edu",
  },
  {
    role: "Internal Coordinator",
    name: "Areg Aslanyan",
    pronouns: "He/Him",
    major: "Computer Science, Psychology",
    year: "Sophomore",
    linkedin:
      "https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://www.linkedin.com/in/areg-aslanyan&ved=2ahUKEwiA5rv5k4qMAxVJF1kFHReAMcAQFnoECCUQAQ&usg=AOvVaw0GT477FJbABMalZ4kesjOx",
    image: "/exec-pictures/areg.jpg",
    email: "AregAslanyan2027@u.northwestern.edu",
  },
  {
    role: "Internal Coordinator",
    name: "Melanie Cuenca",
    pronouns: "She/Her",
    major: "Computer Science, German",
    year: "Sophomore",
    linkedin: "https://www.linkedin.com/in/melanie-cuenca-9272112b6/",
    image: "/exec-pictures/melanie.jpeg",
    email: "MelanieCuenca2027@u.northwestern.edu",
  },
  {
    role: "Treasurer",
    name: "Faris Eltayib",
    pronouns: "He/Him",
    major: "Computer Engineering",
    year: "Sophomore",
    linkedin: "https://www.linkedin.com/in/faris-eltayib-a89709297/",
    image: "/exec-pictures/faris.jpg",
    email: "FarisEltayib2027@u.northwestern.edu",
  },
];

export const executiveMembers2425: ExecMember[] = [
  {
    role: "President",
    name: "Safiya Menk",
    pronouns: "She/Her",
    major: "Computer Science",
    year: "Senior",
    linkedin: "https://www.linkedin.com/in/safiyamenk/",
    image: "https://emergingcoders.org/Safiya.jpeg",
    email: "safiyamenk2025@u.northwestern.edu",
    isFounder: true,
  },
  {
    role: "Vice President",
    name: "Ethan Piñeda",
    pronouns: "He/They",
    major: "Computer Science & Data Science",
    year: "Senior",
    linkedin: "https://www.linkedin.com/in/ethanpineda/",
    image: "https://emergingcoders.org/Ethan.jpeg",
    email: "ethanpineda2025@u.northwestern.edu",
    isFounder: true,
  },
  {
    role: "Secretary",
    name: "Sydney Hoppenworth",
    pronouns: "She/They",
    major: "Computer Science",
    year: "Junior",
    linkedin: "https://www.linkedin.com/in/sydney-hoppenworth",
    image: "https://emergingcoders.org/Sydney.jpg",
    email: "sydneyhoppenworth2026@u.northwestern.edu",
  },
  {
    role: "Marketing Chair",
    name: "Eden Kim",
    pronouns: "She/Her",
    major: "Computer Science",
    year: "Junior",
    linkedin: "",
    image: "https://emergingcoders.org/Eden.jpg",
    email: "edenkim2025@u.northwestern.edu",
  },
  {
    role: "Treasurer",
    name: "Samreen Ibrahim",
    pronouns: "She/Her",
    major: "Computer Science",
    year: "Junior",
    linkedin: "",
    image: "https://emergingcoders.org/Samreen.jpeg",
    email: "",
  },
  {
    role: "Webmaster",
    name: "Desmond Yayra",
    pronouns: "He/They",
    major: "Computer Science",
    year: "Senior",
    linkedin: "https://www.linkedin.com/in/ethanpineda/",
    image: "https://emergingcoders.org/Desmond.jpg",
    email: "desmondadanuty2025@u.northwestern.edu",
  },
  {
    role: "Professional Liaison",
    name: "Yafet Hailu",
    pronouns: "He/Him",
    major: "Computer Engineering & HCI Certificate",
    year: "Junior",
    linkedin: "https://www.linkedin.com/in/yafet-hailu-a8b854205/",
    image: "https://emergingcoders.org/Yafet.jpg",
    email: "YafetHailu2026@u.northwestern.edu",
  },
];

export const foundingExecutiveMembers: ExecMember[] = [
  {
    role: "President",
    name: "Emran Majidy",
    pronouns: "He/Him",
    major: "Computer Science",
    year: "Junior",
    linkedin: "",
    image: "https://emergingcoders.org/placeholder.jpg",
    email: "",
    isFounder: true,
  },
  {
    role: "Vice President",
    name: "Amiin Muse",
    pronouns: "He/Him",
    major: "Computer Science & Data Science",
    year: "Junior",
    linkedin: "",
    image: "https://emergingcoders.org/placeholder.jpg",
    email: "",
    isFounder: true,
  },
  {
    role: "Vice President",
    name: "Chisara Ojiako",
    pronouns: "He/Him",
    major: "Computer Science",
    year: "Junior",
    linkedin: "",
    image: "https://emergingcoders.org/placeholder.jpg",
    email: "",
    isFounder: true,
  },
  {
    role: "Secretary",
    name: "Attzy Rodriguez",
    pronouns: "She/Her",
    major: "Cognitive Science & Design Certificate",
    year: "Junior",
    linkedin: "",
    image: "https://emergingcoders.org/placeholder.jpg",
    email: "",
    isFounder: true,
  },
  {
    role: "Treasurer",
    name: "Safiya Menk",
    pronouns: "She/Her",
    major: "Computer Science",
    year: "Junior",
    linkedin: "",
    image: "https://emergingcoders.org/placeholder.jpg",
    email: "",
    isFounder: true,
  },
  {
    role: "Marketing Chair",
    name: "Audrey Benitez-Rojo",
    pronouns: "She/Her",
    major: "Computer Science",
    year: "Junior",
    linkedin: "",
    image: "https://emergingcoders.org/placeholder.jpg",
    email: "",
    isFounder: true,
  },
  {
    role: "Webmaster",
    name: "Ethan Piñeda",
    pronouns: "He/They",
    major: "Computer Science & Data Science",
    year: "Junior",
    linkedin: "",
    image: "https://emergingcoders.org/placeholder.jpg",
    email: "",
    isFounder: true,
  },
  {
    role: "Professional Liaison",
    name: "Donell Makuvire",
    pronouns: "He/Him",
    major: "Computer Science",
    year: "Sophomore",
    linkedin: "",
    image: "https://emergingcoders.org/placeholder.jpg",
    email: "",
    isFounder: true,
  },
];

export const ExecutiveBoard20232024: ExecMember[] = [
  {
    role: "President",
    name: "Emran Majidy",
    pronouns: "He/Him",
    major: "Computer Science",
    year: "Junior",
    linkedin: "",
    image: "https://emergingcoders.org/placeholder.jpg",
    email: "",
    isFounder: true,
  },
  {
    role: "Vice President",
    name: "Amiin Muse",
    pronouns: "He/Him",
    major: "Computer Science & Data Science",
    year: "Junior",
    linkedin: "",
    image: "https://emergingcoders.org/placeholder.jpg",
    email: "",
    isFounder: true,
  },
  {
    role: "Vice President",
    name: "Chisara Ojiako",
    pronouns: "He/Him",
    major: "Computer Science",
    year: "Junior",
    linkedin: "",
    image: "https://emergingcoders.org/placeholder.jpg",
    email: "",
    isFounder: true,
  },
  {
    role: "Secretary",
    name: "Attzy Rodriguez",
    pronouns: "She/Her",
    major: "Cognitive Science & Design Certificate",
    year: "Junior",
    linkedin: "",
    image: "https://emergingcoders.org/placeholder.jpg",
    email: "",
    isFounder: true,
  },
  {
    role: "Treasurer",
    name: "Safiya Menk",
    pronouns: "She/Her",
    major: "Computer Science",
    year: "Junior",
    linkedin: "",
    image: "https://emergingcoders.org/placeholder.jpg",
    email: "",
    isFounder: true,
  },
  {
    role: "Marketing Chair",
    name: "Audrey Benitez-Rojo",
    pronouns: "She/Her",
    major: "Computer Science",
    year: "Junior",
    linkedin: "",
    image: "https://emergingcoders.org/placeholder.jpg",
    email: "",
    isFounder: true,
  },
  {
    role: "Webmaster",
    name: "Ethan Piñeda",
    pronouns: "He/They",
    major: "Computer Science & Data Science",
    year: "Junior",
    linkedin: "",
    image: "https://emergingcoders.org/placeholder.jpg",
    email: "",
    isFounder: true,
  },
  {
    role: "Professional Liaison",
    name: "Donell Makuvire",
    pronouns: "He/Him",
    major: "Computer Science",
    year: "Sophomore",
    linkedin: "",
    image: "https://emergingcoders.org/placeholder.jpg",
    email: "",
    isFounder: true,
  },
];
