import type { ExecMember } from "@/types/exec-board-type";

export const juniorExecutiveMembers: ExecMember[] = [
  {
    role: "Junior Exec Board Member",
    name: "Acton Healy",
    pronouns: "He/Him",
    major: "Computer Science",
    year: "Freshman",
    linkedin: "",
    image: "https://emergingcoders.org/jeb_2024/Acton.jpeg",
    email: "actonhealy2028@u.northwestern.edu",
  },
  {
    role: "Junior Exec Board Member",
    name: "Xiaolin Liu",
    pronouns: "She/Her",
    major: "Computer Science & Data Science",
    year: "Junior",
    linkedin: "",
    image: "https://emergingcoders.org/jeb_2024/Xiaolin%20Liu.jpeg",
    email: "xiaolinliu2026@u.northwestern.edu",
  },
  {
    role: "Junior Exec Board Member",
    name: "Lana Alnajm",
    pronouns: "She/Her",
    major: "Computer Science & Legal Studies",
    year: "Freshman",
    linkedin: "",
    image: "https://emergingcoders.org/jeb_2024/Lana.jpeg",
    email: "lanaalnajm@gmail.com",
  },
  {
    role: "Junior Exec Board Member",
    name: "Faris Eltayib",
    pronouns: "He/Him",
    major: "Computer Engineering",
    year: "Sophomore",
    linkedin: "",
    image: "https://emergingcoders.org/jeb_2024/Eltayib.jpg",
    email: "fariseltayib2027@u.northwestern.edu",
  },
  {
    role: "Junior Exec Board Member",
    name: "Joanna Echeverri",
    pronouns: "She/Her",
    major: "Computer Science",
    year: "Sophomore",
    linkedin: "",
    image: "https://emergingcoders.org/jeb_2024/Joanna.jpg",
    email: "joannaecheverriporras2027@u.northwestern.edu",
  },
  {
    role: "Junior Exec Board Member",
    name: "Alejandro Chavarria",
    pronouns: "He/Him",
    major: "Industrial Engineering",
    year: "Junior",
    linkedin: "",
    image: "https://emergingcoders.org/jeb_2024/Alejandro.jpg",
    email: "alejandrochavarriagonzalez2026@u.northwestern.edu",
  },
  {
    role: "Junior Exec Board Member",
    name: "Abem Girmai",
    pronouns: "He/Him",
    major: "Computer Science",
    year: "Freshman",
    linkedin: "",
    image: "https://emergingcoders.org/jeb_2024/Abem.jpg",
    email: "abemgirmai2028@u.northwestern.edu",
  },
  {
    role: "Junior Exec Board Member",
    name: "Omotayo Oludemi",
    pronouns: "He/Him",
    major: "Computer Science",
    year: "Sophomore",
    linkedin: "",
    image: "https://emergingcoders.org/jeb_2024/Omotayo.jpeg",
    email: "omotayooludemi2027@u.northwestern.edu",
  },

  {
    role: "Junior Exec Board Member",
    name: "Marissa Rocha",
    pronouns: "She/Her",
    major: "Computer Science",
    year: "Freshman",
    linkedin: "",
    image: "https://emergingcoders.org/jeb_2024/Marissa.jpeg",
    email: "marissarocharangel2028@u.northwestern.edu",
  },

  {
    role: "Junior Exec Board Member",
    name: "Diego Perez-Aguilar",
    pronouns: "He/Him",
    major: "Computer Science",
    year: "Freshman",
    linkedin: "",
    image: "https://emergingcoders.org/jeb_2024/Perez-Aguilar.jpeg",
    email: "diegoperez-aguilar2028@u.northwestern.edu",
  },
];
