import type { ExecMember } from '@/types/exec-board-type';

export const juniorExecutiveMembers2627: ExecMember[] = [];

export const juniorExecutiveMembers2526: ExecMember[] = [
  {
    role: 'JEB Member',
    name: 'Gabriela Avila',
    pronouns: 'She/Her',
    major: 'Computer Engineering',
    year: 'Sophomore',
    linkedin: 'www.linkedin.com/in/gabriela-avila15',
    image: '/exec-pictures/gabriela_avila.jpg',
    email: 'GabrielaAvila2028@u.northwestern.edu',
  },
  {
    role: 'JEB Member',
    name: 'Abem Girmai',
    pronouns: 'He/Him',
    major: 'Computer Science',
    year: 'Sophomore',
    linkedin: 'https://www.linkedin.com/in/abemgirmai/',
    image: '/exec-pictures/abem_girmai.jpg',
    email: 'agirmai737@gmail.com',
  },
  {
    role: 'JEB Member',
    name: 'Tais Martinez',
    pronouns: 'She/Her',
    major: 'Computer Science and Data Science',
    year: 'Sophmore',
    linkedin: 'https://www.linkedin.com/in/taismartinez/',
    image: '/exec-pictures/tais_martinez.jpg',
    email: 'TaisMartinez2028.1@u.northwestern.edu',
  },
  {
    role: 'JEB Member',
    name: 'Diego Perez-Aguilar',
    pronouns: 'He/Him',
    major: 'Computer Science',
    year: 'Sophomore',
    linkedin: 'https://www.linkedin.com/in/diego-purr-agua/',
    image: '/exec-pictures/diego_perez_aguilar.jpg',
    email: 'DiegoPerez-Aguilar2028@u.northwestern.edu',
  },
  {
    role: 'JEB Member',
    name: 'Zara Ahmar',
    pronouns: 'She/Her',
    major: 'Computer Science and Data Science',
    year: 'Sophomore',
    linkedin: 'https://www.linkedin.com/in/zara-ahmar-421336299/',
    image: '/exec-pictures/zara_ahmar.jpg',
    email: 'ZaraAhmar2028@u.northwestern.edu',
  },
  {
    role: 'JEB Member',
    name: 'Reid Strickland',
    pronouns: 'He/Him',
    major: 'Computer Science',
    year: 'Freshman',
    linkedin: '',
    image: '/exec-pictures/reid_strickland.jpg',
    email: 'NathanielBroughton2029@u.northwestern.edu',
  },
  {
    role: 'JEB Member',
    name: 'Kevin Mei',
    pronouns: 'She/Her',
    major: 'Computer Science and Journalism',
    year: 'Sophomore',
    linkedin: 'https://www.linkedin.com/in/kmeixyz/',
    image: '/exec-pictures/kevin_mei.jpg',
    email: 'KevinMei2028@u.northwestern.edu',
  },
];

export const juniorExecutiveMembers2425: ExecMember[] = [
  {
    role: 'Junior Exec Board Member',
    name: 'Keigo Healy',
    pronouns: 'He/Him',
    major: 'Computer Science',
    year: 'Freshman',
    linkedin: '',
    image: 'https://emergingcoders.org/jeb_2024/keigo.jpeg',
    email: 'keigohealy2028@u.northwestern.edu',
  },
  {
    role: 'Junior Exec Board Member',
    name: 'Xiaolin Liu',
    pronouns: 'She/Her',
    major: 'Computer Science & Data Science',
    year: 'Junior',
    linkedin: '',
    image: 'https://emergingcoders.org/jeb_2024/Xiaolin%20Liu.jpeg',
    email: 'xiaolinliu2026@u.northwestern.edu',
  },
  {
    role: 'Junior Exec Board Member',
    name: 'Lana Alnajm',
    pronouns: 'She/Her',
    major: 'Computer Science & Legal Studies',
    year: 'Freshman',
    linkedin: '',
    image: 'https://emergingcoders.org/jeb_2024/Lana.jpeg',
    email: 'lanaalnajm@gmail.com',
  },
  {
    role: 'Junior Exec Board Member',
    name: 'Faris Eltayib',
    pronouns: 'He/Him',
    major: 'Computer Engineering',
    year: 'Sophomore',
    linkedin: '',
    image: 'https://emergingcoders.org/jeb_2024/Eltayib.jpg',
    email: 'fariseltayib2027@u.northwestern.edu',
  },
  {
    role: 'Junior Exec Board Member',
    name: 'Joanna Echeverri',
    pronouns: 'She/Her',
    major: 'Computer Science',
    year: 'Sophomore',
    linkedin: '',
    image: 'https://emergingcoders.org/jeb_2024/Joanna.jpg',
    email: 'joannaecheverriporras2027@u.northwestern.edu',
  },
  {
    role: 'Junior Exec Board Member',
    name: 'Alejandro Chavarria',
    pronouns: 'He/Him',
    major: 'Industrial Engineering',
    year: 'Junior',
    linkedin: '',
    image: 'https://emergingcoders.org/jeb_2024/Alejandro.jpg',
    email: 'alejandrochavarriagonzalez2026@u.northwestern.edu',
  },
  {
    role: 'Junior Exec Board Member',
    name: 'Abem Girmai',
    pronouns: 'He/Him',
    major: 'Computer Science',
    year: 'Freshman',
    linkedin: '',
    image: 'https://emergingcoders.org/jeb_2024/Abem.jpg',
    email: 'abemgirmai2028@u.northwestern.edu',
  },
  {
    role: 'Junior Exec Board Member',
    name: 'Omotayo Oludemi',
    pronouns: 'He/Him',
    major: 'Computer Science',
    year: 'Sophomore',
    linkedin: '',
    image: 'https://emergingcoders.org/jeb_2024/Omotayo.jpeg',
    email: 'omotayooludemi2027@u.northwestern.edu',
  },

  {
    role: 'Junior Exec Board Member',
    name: 'Marissa Rocha',
    pronouns: 'She/Her',
    major: 'Computer Science',
    year: 'Freshman',
    linkedin: '',
    image: 'https://emergingcoders.org/jeb_2024/Marissa.jpeg',
    email: 'marissarocharangel2028@u.northwestern.edu',
  },

  {
    role: 'Junior Exec Board Member',
    name: 'Diego Perez-Aguilar',
    pronouns: 'He/Him',
    major: 'Computer Science',
    year: 'Freshman',
    linkedin: '',
    image: 'https://emergingcoders.org/jeb_2024/Perez-Aguilar.jpeg',
    email: 'diegoperez-aguilar2028@u.northwestern.edu',
  },
];

export const foundingJuniorExecutiveMembers: ExecMember[] = [
  {
    role: 'Junior Exec Board Member',
    name: 'Kathy Cui',
    pronouns: 'She/Her',
    major: 'Computer Science',
    year: 'Sophomore',
    linkedin: '',
    image: 'https://emergingcoders.org/placeholder.jpg',
    email: '',
  },
  {
    role: 'Junior Exec Board Member',
    name: 'Yafet Hailu',
    pronouns: 'He/Him',
    major: 'Computer Engineering & HCI Certificate',
    year: 'Sophomore',
    linkedin: '',
    image: 'https://emergingcoders.org/placeholder.jpg',
    email: '',
  },
  {
    role: 'Junior Exec Board Member',
    name: 'Mukhtar Handulle',
    pronouns: 'He/Him',
    major: 'Computer Science',
    year: 'Freshman',
    linkedin: '',
    image: 'https://emergingcoders.org/placeholder.jpg',
    email: '',
  },
  {
    role: 'Junior Exec Board Member',
    name: 'Sydney Hoppenworth',
    pronouns: 'She/They',
    major: 'Computer Science',
    year: 'Sophomore',
    linkedin: '',
    image: 'https://emergingcoders.org/placeholder.jpg',
    email: '',
  },
  {
    role: 'Junior Exec Board Member',
    name: 'Eden Kim',
    pronouns: 'She/Her',
    major: 'Computer Science',
    year: 'Junior',
    linkedin: '',
    image: 'https://emergingcoders.org/placeholder.jpg',
    email: '',
  },
  {
    role: 'Junior Exec Board Member',
    name: 'Ariel Garcia',
    pronouns: 'He/Him',
    major: 'Computer Science',
    year: 'Freshman',
    linkedin: '',
    image: 'https://emergingcoders.org/placeholder.jpg',
    email: '',
  },
  {
    role: 'Junior Exec Board Member',
    name: 'Samreen Ibrahim',
    pronouns: 'She/Her',
    major: 'Computer Science',
    year: 'Sophomore',
    linkedin: '',
    image: 'https://emergingcoders.org/placeholder.jpg',
    email: '',
  },
  {
    role: 'Junior Exec Board Member',
    name: 'Arturo Fonseca',
    pronouns: 'He/Him',
    major: 'Computer Science & Data Science',
    year: 'Junior',
    linkedin: '',
    image: 'https://emergingcoders.org/placeholder.jpg',
    email: '',
  },
];
