// import AnnouncementBanner from '@/components/announcement-banner';
import CTA from '@/components/cta';
import Footer from '@/components/footer';
import Header from '@/components/navigation/header';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Emerging Coders',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <AnnouncementBanner /> */}
        <div className='flex min-h-screen flex-col overflow-hidden'>
          <Header />
          {children}
          <CTA />
          <Footer />
        </div>
      </body>
    </html>
  );
}
