const execBoard2024 = [
    {
        role: "President",
        name: "Safiya Menk",
        pronouns: "She/Her",
        major: "Computer Science",
        classStanding: "Seniorr",
        linkedin: "https://www.linkedin.com/in/safiyamenk/",
        img: "/Safiya.jpeg",
        email: "safiyamenk2025@u.northwestern.edu", 
        website: "", 
        founder: true,
    },

    {
        role: "Vice President",
        name: "Ethan Piñeda",
        pronouns: "He/They",
        major: "Computer Science & Data Science",
        classStanding: "Senior",
        linkedin: "https://www.linkedin.com/in/ethanpineda/",
        img: "/Ethan.jpeg",
        email: "ethanpineda2025@u.northwestern.edu",
        website: "https://ethanpaneraa.github.io/Ethan/", 
        founder: true, 
    },


    {
        role: "Secretary",
        name: "Sydney Hoppenworth", 
        pronouns: "She/They",
        major: "Computer Science",
        classStanding: "Junior",
        linkedin: "https://www.linkedin.com/in/sydney-hoppenworth", 
        img: "/Sydney.jpg",
        email: "sydneyhoppenworth2026@u.northwestern.edu", 
        website: "",
    },
    
     

    {
        role: "Social Media Chair",
        name: "Eden Kim", 
        pronouns: "She/Her",
        major: "Computer Science",
        classStanding: "Senior",
        linkedin: "",
        img: "/Eden.jpg",
        email: "edenkim2025@u.northwestern.edu", 
        website: "",
    },

    {
        role: "Treasurer", 
        name: "Samreen Ibrahim",
        pronouns: "She/Her",
        major: "Computer Science",
        classStanding: "Junior",
        linkedin: "",
        img: "/Samreen.jpeg",
        email: "",
        website: "",
    }, 
    
    {
        role: "Webmaster",
        name: "Desmond Yayra",
        pronouns: "He/They",
        major: "Computer Science",
        classStanding: "Senior",
        linkedin: "https://www.linkedin.com/in/ethanpineda/",
        img: "/Desmond.jpg",
        email: "desmondadanuty2025@u.northwestern.edu",
        website: "https://ethanpaneraa.github.io/Ethan/", 
    },
    
    {
        role: "Professional Liason", 
        name: "Yafet Hailu", 
        pronouns: "He/Him",
        major: "Computer Engineering & HCI Certificate",
        classStanding: "Junior",
        linkedin: "https://www.linkedin.com/in/yafet-hailu-a8b854205/",
        img: "/Yafet.jpg",
        email: "YafetHailu2026@u.northwestern.edu", 
        website: "", 
    },
];

const juniorExecBoard2024 = [
    {
        role: "Junior Exec Board Member",
        name: "Kathy Cui",
        pronouns: "She/Her", 
        major: "Computer Science", 
        classStanding: "Sophomore",
        linkedin: "https://www.linkedin.com/in/",
        img: "/Kat.jpg", 
        email: "KathyCui2026@u.northwestern.edu", 
        website: "", 
    }, 
    {
        role: "Junior Exec Board Member", 
        name: "Yafet Hailu", 
        pronouns: "He/Him",
        major: "Computer Engineering & HCI Certificate",
        classStanding: "Sophomore",
        linkedin: "https://www.linkedin.com/in/yafet-hailu-a8b854205/",
        img: "/Yafet.jpg",
        email: "YafetHailu2026@u.northwestern.edu", 
        website: "", 
    }, 
    {
        role: "Junior Exec Board Member",
        name: "Mukhtar Handulle", 
        pronouns: "He/Him",
        major: "Computer Science",
        classStanding: "Freshmen",
        linkedin: "https://www.linkedin.com/in/mukhtar-handulle", 
        img: "/Mukhtar.jpg",
        email: "MukhtarHandulle2027@u.northwestern.edu", 
        website: "", 
    }, 
    {
        role: "Junior Exec Board Member",
        name: "Sydney Hoppenworth", 
        pronouns: "She/They",
        major: "Computer Science",
        classStanding: "Sophomore",
        linkedin: "https://www.linkedin.com/in/sydney-hoppenworth", 
        img: "/Sydney.jpg",
        email: "sydneyhoppenworth2026@u.northwestern.edu", 
        website: "",
    },
    {
        role: "Junior Exec Board Member",
        name: "Eden Kim", 
        pronouns: "She/Her",
        major: "Computer Science",
        classStanding: "Junior",
        linkedin: "",
        img: "/Eden.jpg",
        email: "edenkim2025@u.northwestern.edu", 
        website: "",
    }, 
    {
        role: "Junior Exec Board Member",
        name: "Ariel Garcia", 
        pronouns: "He/Him",
        major: "Computer Science",
        classStanding: "Freshmen",
        linkedin: "",
        img: "/Ariel.jpg",
        email: "ArielGarcia2027@u.northwestern.edu", 
        website: "",
    }, 
    {
        role: "Junior Exec Board Member", 
        name: "Samreen Ibrahim",
        pronouns: "She/Her",
        major: "Computer Science",
        classStanding: "Sophomore",
        linkedin: "",
        img: "/Samreen.jpeg",
        email: "",
        website: "",
    }, 
    {
        role: "Junior Exec Board Member", 
        name: "Arturo Fonseca", 
        pronouns: "He/Him",
        major: "Computer Science & Data Science",
        classStanding: "Junior",
        linkedin: "https://www.linkedin.com/in/arturo-f/",
        img: "/Arturo.jpeg",
        email: "",
        website: "",
    },
]

export { execBoard2024, juniorExecBoard2024 };