const execBoard2024 = [
  {
    role: "President",
    name: "Safiya Menk",
    pronouns: "She/Her",
    major: "Computer Science",
    classStanding: "Senior",
    linkedin: "https://www.linkedin.com/in/safiyamenk/",
    img: "/Safiya.jpeg",
    email: "safiyamenk2025@u.northwestern.edu",
    website: "",
    founder: true,
  },
  {
    role: "Vice President",
    name: "Ethan Piñeda",
    pronouns: "He/They",
    major: "Computer Science & Data Science",
    classStanding: "Senior",
    linkedin: "https://www.linkedin.com/in/ethanpineda/",
    img: "/Ethan.jpeg",
    email: "ethanpineda2025@u.northwestern.edu",
    website: "https://ethanpaneraa.github.io/Ethan/",
    founder: true,
  },
  {
    role: "Secretary",
    name: "Sydney Hoppenworth",
    pronouns: "She/They",
    major: "Computer Science",
    classStanding: "Junior",
    linkedin: "https://www.linkedin.com/in/sydney-hoppenworth",
    img: "/Sydney.jpg",
    email: "sydneyhoppenworth2026@u.northwestern.edu",
    website: "",
  },
  {
    role: "Social Media Chair",
    name: "Eden Kim",
    pronouns: "She/Her",
    major: "Computer Science",
    classStanding: "Junior",
    linkedin: "",
    img: "/Eden.jpg",
    email: "edenkim2025@u.northwestern.edu",
    website: "",
  },
  {
    role: "Treasurer",
    name: "Samreen Ibrahim",
    pronouns: "She/Her",
    major: "Computer Science",
    classStanding: "Junior",
    linkedin: "",
    img: "/Samreen.jpeg",
    email: "",
    website: "",
  },
  {
    role: "Webmaster",
    name: "Desmond Yayra",
    pronouns: "He/They",
    major: "Computer Science",
    classStanding: "Senior",
    linkedin: "https://www.linkedin.com/in/ethanpineda/",
    img: "/Desmond.jpg",
    email: "desmondadanuty2025@u.northwestern.edu",
    website: "https://ethanpaneraa.github.io/Ethan/",
  },
  {
    role: "Professional Liaison",
    name: "Yafet Hailu",
    pronouns: "He/Him",
    major: "Computer Engineering & HCI Certificate",
    classStanding: "Junior",
    linkedin: "https://www.linkedin.com/in/yafet-hailu-a8b854205/",
    img: "/Yafet.jpg",
    email: "YafetHailu2026@u.northwestern.edu",
    website: "",
  },
];

const juniorExecBoard2024 = [
  {
    role: "Junior Exec Board Member",
    name: "Acton Healy",
    pronouns: "He/Him",
    major: "Computer Science",
    classStanding: "Freshman",
    linkedin: "",
    img: "/jeb_2024/Acton.jpeg",
    email: "actonhealy2028@u.northwestern.edu",
    website: "",
  },
  {
    role: "Junior Exec Board Member",
    name: "Xiaolin Liu",
    pronouns: "She/Her",
    major: "Computer Science & Data Science",
    classStanding: "Junior",
    linkedin: "",
    img: "/jeb_2024/Xiaolin Liu.jpeg",
    email: "xiaolinliu2026@u.northwestern.edu",
    website: "",
  },
  {
    role: "Junior Exec Board Member",
    name: "Lana Alnajm",
    pronouns: "She/Her",
    major: "Computer Science & Legal Studies",
    classStanding: "Freshman",
    linkedin: "",
    img: "/jeb_2024/Lana.jpeg",
    email: "lanaalnajm@gmail.com",
    website: "",
  },
  {
    role: "Junior Exec Board Member",
    name: "Faris Eltayib",
    pronouns: "He/Him",
    major: "Computer Engineering",
    classStanding: "Sophomore",
    linkedin: "",
    img: "/jeb_2024/Eltayib.jpg",
    email: "fariseltayib2027@u.northwestern.edu",
    website: "",
  },
  {
    role: "Junior Exec Board Member",
    name: "Joanna Echeverri",
    pronouns: "She/Her",
    major: "Computer Science",
    classStanding: "Sophomore",
    linkedin: "",
    img: "/jeb_2024/Joanna.jpg",
    email: "joannaecheverriporras2027@u.northwestern.edu",
    website: "",
  },
  {
    role: "Junior Exec Board Member",
    name: "Alejandro Chavarria",
    pronouns: "He/Him",
    major: "Industrial Engineering",
    classStanding: "Junior",
    linkedin: "",
    img: "/jeb_2024/Alejandro.jpg",
    email: "alejandrochavarriagonzalez2026@u.northwestern.edu",
    website: "",
  },
  {
    role: "Junior Exec Board Member",
    name: "Abem Girmai",
    pronouns: "He/Him",
    major: "Computer Science",
    classStanding: "Freshman",
    linkedin: "",
    img: "/jeb_2024/Abem.jpg",
    email: "abemgirmai2028@u.northwestern.edu",
    website: "",
  },
  {
    role: "Junior Exec Board Member",
    name: "Omotayo Oludemi",
    pronouns: "He/Him",
    major: "Computer Science",
    classStanding: "Sophomore",
    linkedin: "",
    img: "/jeb_2024/Omotayo.jpeg",
    email: "omotayooludemi2027@u.northwestern.edu",
    website: "",
  },

  {
    role: "Junior Exec Board Member",
    name: "Marissa Rocha",
    pronouns: "She/Her",
    major: "Computer Science",
    classStanding: "Freshman",
    linkedin: "",
    img: "/jeb_2024/Marissa.jpeg",
    email: "marissarocharangel2028@u.northwestern.edu",
    website: "",
  },

  {
    role: "Junior Exec Board Member",
    name: "Diego Perez-Aguilar",
    pronouns: "He/Him",
    major: "Computer Science",
    classStanding: "Freshman",
    linkedin: "",
    img: "/jeb_2024/Perez-Aguilar.jpeg",
    email: "diegoperez-aguilar2028@u.northwestern.edu",
    website: "",
  },
];

export { execBoard2024, juniorExecBoard2024 };
