const getImagePath = (imageName) => {
  const basePath =
    process.env.NODE_ENV === "production" ? "/Emerging-Coders-Website" : "";
  return `${basePath}${imageName}`;
};

const execBoard2024 = [
  {
    role: "President",
    name: "Safiya Menk",
    pronouns: "She/Her",
    major: "Computer Science",
    classStanding: "Seniorr",
    linkedin: "https://www.linkedin.com/in/safiyamenk/",
    img: getImagePath("/Safiya.jpeg"),
    email: "safiyamenk2025@u.northwestern.edu",
    website: "",
    founder: true,
  },
  {
    role: "Vice President",
    name: "Ethan Piñeda",
    pronouns: "He/They",
    major: "Computer Science & Data Science",
    classStanding: "Senior",
    linkedin: "https://www.linkedin.com/in/ethanpineda/",
    img: getImagePath("/Ethan.jpeg"),
    email: "ethanpineda2025@u.northwestern.edu",
    website: "https://ethanpaneraa.github.io/Ethan/",
    founder: true,
  },
  {
    role: "Secretary",
    name: "Sydney Hoppenworth",
    pronouns: "She/They",
    major: "Computer Science",
    classStanding: "Junior",
    linkedin: "https://www.linkedin.com/in/sydney-hoppenworth",
    img: getImagePath("/Sydney.jpg"),
    email: "sydneyhoppenworth2026@u.northwestern.edu",
    website: "",
  },
  {
    role: "Social Media Chair",
    name: "Eden Kim",
    pronouns: "She/Her",
    major: "Computer Science",
    classStanding: "Senior",
    linkedin: "",
    img: getImagePath("/Eden.jpg"),
    email: "edenkim2025@u.northwestern.edu",
    website: "",
  },
  {
    role: "Treasurer",
    name: "Samreen Ibrahim",
    pronouns: "She/Her",
    major: "Computer Science",
    classStanding: "Junior",
    linkedin: "",
    img: getImagePath("/Samreen.jpeg"),
    email: "",
    website: "",
  },
  {
    role: "Webmaster",
    name: "Desmond Yayra",
    pronouns: "He/They",
    major: "Computer Science",
    classStanding: "Senior",
    linkedin: "https://www.linkedin.com/in/ethanpineda/",
    img: getImagePath("/Desmond.jpg"),
    email: "desmondadanuty2025@u.northwestern.edu",
    website: "https://ethanpaneraa.github.io/Ethan/",
  },
  {
    role: "Professional Liason",
    name: "Yafet Hailu",
    pronouns: "He/Him",
    major: "Computer Engineering & HCI Certificate",
    classStanding: "Junior",
    linkedin: "https://www.linkedin.com/in/yafet-hailu-a8b854205/",
    img: getImagePath("/Yafet.jpg"),
    email: "YafetHailu2026@u.northwestern.edu",
    website: "",
  },
];

const juniorExecBoard2024 = [
  {
    role: "Junior Exec Board Member",
    name: "Kathy Cui",
    pronouns: "She/Her",
    major: "Computer Science",
    classStanding: "Sophomore",
    linkedin: "https://www.linkedin.com/in/",
    img: getImagePath("/Kat.jpg"),
    email: "KathyCui2026@u.northwestern.edu",
    website: "",
  },
  {
    role: "Junior Exec Board Member",
    name: "Yafet Hailu",
    pronouns: "He/Him",
    major: "Computer Engineering & HCI Certificate",
    classStanding: "Sophomore",
    linkedin: "https://www.linkedin.com/in/yafet-hailu-a8b854205/",
    img: getImagePath("/Yafet.jpg"),
    email: "YafetHailu2026@u.northwestern.edu",
    website: "",
  },
  {
    role: "Junior Exec Board Member",
    name: "Mukhtar Handulle",
    pronouns: "He/Him",
    major: "Computer Science",
    classStanding: "Freshmen",
    linkedin: "https://www.linkedin.com/in/mukhtar-handulle",
    img: getImagePath("/Mukhtar.jpg"),
    email: "MukhtarHandulle2027@u.northwestern.edu",
    website: "",
  },
  {
    role: "Junior Exec Board Member",
    name: "Sydney Hoppenworth",
    pronouns: "She/They",
    major: "Computer Science",
    classStanding: "Sophomore",
    linkedin: "https://www.linkedin.com/in/sydney-hoppenworth",
    img: getImagePath("/Sydney.jpg"),
    email: "sydneyhoppenworth2026@u.northwestern.edu",
    website: "",
  },
  {
    role: "Junior Exec Board Member",
    name: "Eden Kim",
    pronouns: "She/Her",
    major: "Computer Science",
    classStanding: "Junior",
    linkedin: "",
    img: getImagePath("/Eden.jpg"),
    email: "edenkim2025@u.northwestern.edu",
    website: "",
  },
  {
    role: "Junior Exec Board Member",
    name: "Ariel Garcia",
    pronouns: "He/Him",
    major: "Computer Science",
    classStanding: "Freshmen",
    linkedin: "",
    img: getImagePath("/Ariel.jpg"),
    email: "ArielGarcia2027@u.northwestern.edu",
    website: "",
  },
  {
    role: "Junior Exec Board Member",
    name: "Samreen Ibrahim",
    pronouns: "She/Her",
    major: "Computer Science",
    classStanding: "Sophomore",
    linkedin: "",
    img: getImagePath("/Samreen.jpeg"),
    email: "",
    website: "",
  },
  {
    role: "Junior Exec Board Member",
    name: "Arturo Fonseca",
    pronouns: "He/Him",
    major: "Computer Science & Data Science",
    classStanding: "Junior",
    linkedin: "https://www.linkedin.com/in/arturo-f/",
    img: getImagePath("/Arturo.jpeg"),
    email: "",
    website: "",
  },
];

export { execBoard2024, juniorExecBoard2024 };
